#
# Copyright (C) 2025 Julien Viet
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
./conformance_test_runner --enforce_recommended --maximum_edition PROTO3 --output_dir . \
--test Recommended.Proto3.JsonInput.BytesFieldBase64Url.ProtobufOutput \
--test Recommended.Proto3.JsonInput.FieldNameWithDoubleUnderscores.ProtobufOutput \
--test Recommended.Proto3.JsonInput.IgnoreUnknownEnumStringValueInMapPart.ProtobufOutput \
--test Recommended.Proto3.JsonInput.IgnoreUnknownEnumStringValueInMapValue.ProtobufOutput \
--test Recommended.Proto3.JsonInput.IgnoreUnknownEnumStringValueInOptionalField.ProtobufOutput \
--test Recommended.Proto3.JsonInput.IgnoreUnknownEnumStringValueInRepeatedField.ProtobufOutput \
--test Recommended.Proto3.JsonInput.IgnoreUnknownEnumStringValueInRepeatedPart.ProtobufOutput \
--test Recommended.Proto3.JsonInput.MultilineNoSpaces.ProtobufOutput \
--test Recommended.Proto3.JsonInput.MultilineWithSpaces.ProtobufOutput \
--test Recommended.Proto3.JsonInput.OneLineNoSpaces.ProtobufOutput \
--test Recommended.Proto3.JsonInput.OneLineWithSpaces.ProtobufOutput \
--test Recommended.Proto3.JsonInput.OneofZeroBool.ProtobufOutput \
--test Recommended.Proto3.JsonInput.OneofZeroBytes.ProtobufOutput \
--test Recommended.Proto3.JsonInput.OneofZeroDouble.ProtobufOutput \
--test Recommended.Proto3.JsonInput.OneofZeroEnum.ProtobufOutput \
--test Recommended.Proto3.JsonInput.OneofZeroFloat.ProtobufOutput \
--test Recommended.Proto3.JsonInput.OneofZeroMessage.ProtobufOutput \
--test Recommended.Proto3.JsonInput.OneofZeroString.ProtobufOutput \
--test Recommended.Proto3.JsonInput.OneofZeroUint32.ProtobufOutput \
--test Recommended.Proto3.JsonInput.OneofZeroUint64.ProtobufOutput \
--test Required.Proto3.JsonInput.AllFieldAcceptNull.ProtobufOutput \
--test Required.Proto3.JsonInput.Any.ProtobufOutput \
--test Required.Proto3.JsonInput.AnyNested.ProtobufOutput \
--test Required.Proto3.JsonInput.AnyUnorderedTypeTag.ProtobufOutput \
--test Required.Proto3.JsonInput.AnyWithDuration.ProtobufOutput \
--test Required.Proto3.JsonInput.AnyWithFieldMask.ProtobufOutput \
--test Required.Proto3.JsonInput.AnyWithInt32ValueWrapper.ProtobufOutput \
--test Required.Proto3.JsonInput.AnyWithStruct.ProtobufOutput \
--test Required.Proto3.JsonInput.AnyWithTimestamp.ProtobufOutput \
--test Required.Proto3.JsonInput.AnyWithValueForInteger.ProtobufOutput \
--test Required.Proto3.JsonInput.AnyWithValueForJsonObject.ProtobufOutput \
--test Required.Proto3.JsonInput.BoolFieldFalse.ProtobufOutput \
--test Required.Proto3.JsonInput.BoolFieldTrue.ProtobufOutput \
--test Required.Proto3.JsonInput.BoolMapEscapedKey.ProtobufOutput \
--test Required.Proto3.JsonInput.BoolMapField.ProtobufOutput \
--test Required.Proto3.JsonInput.BytesField.ProtobufOutput \
--test Required.Proto3.JsonInput.BytesRepeatedField.ProtobufOutput \
--test Required.Proto3.JsonInput.DoubleFieldInfinity.ProtobufOutput \
--test Required.Proto3.JsonInput.DoubleFieldMaxNegativeValue.ProtobufOutput \
--test Required.Proto3.JsonInput.DoubleFieldMaxPositiveValue.ProtobufOutput \
--test Required.Proto3.JsonInput.DoubleFieldMinNegativeValue.ProtobufOutput \
--test Required.Proto3.JsonInput.DoubleFieldMinPositiveValue.ProtobufOutput \
--test Required.Proto3.JsonInput.DoubleFieldNan.ProtobufOutput \
--test Required.Proto3.JsonInput.DoubleFieldNegativeInfinity.ProtobufOutput \
--test Required.Proto3.JsonInput.DoubleFieldQuotedValue.ProtobufOutput \
--test Required.Proto3.JsonInput.DurationMaxValue.ProtobufOutput \
--test Required.Proto3.JsonInput.DurationMinValue.ProtobufOutput \
--test Required.Proto3.JsonInput.DurationNegativeNanos.ProtobufOutput \
--test Required.Proto3.JsonInput.DurationNegativeSeconds.ProtobufOutput \
--test Required.Proto3.JsonInput.DurationNull.ProtobufOutput \
--test Required.Proto3.JsonInput.DurationRepeatedValue.ProtobufOutput \
--test Required.Proto3.JsonInput.EmptyFieldMask.ProtobufOutput \
--test Required.Proto3.JsonInput.EnumField.ProtobufOutput \
--test Required.Proto3.JsonInput.EnumFieldNumericValueNonZero.ProtobufOutput \
--test Required.Proto3.JsonInput.EnumFieldNumericValueZero.ProtobufOutput \
--test Required.Proto3.JsonInput.EnumFieldWithAlias.ProtobufOutput \
--test Required.Proto3.JsonInput.EnumFieldWithAliasDifferentCase.ProtobufOutput \
--test Required.Proto3.JsonInput.EnumFieldWithAliasLowerCase.ProtobufOutput \
--test Required.Proto3.JsonInput.EnumFieldWithAliasUseAlias.ProtobufOutput \
--test Required.Proto3.JsonInput.EnumRepeatedField.ProtobufOutput \
--test Required.Proto3.JsonInput.FieldMask.ProtobufOutput \
--test Required.Proto3.JsonInput.FieldNameEscaped.ProtobufOutput \
--test Required.Proto3.JsonInput.FieldNameInSnakeCase.ProtobufOutput \
--test Required.Proto3.JsonInput.FieldNameWithMixedCases.ProtobufOutput \
--test Required.Proto3.JsonInput.FieldNameWithNumbers.ProtobufOutput \
--test Required.Proto3.JsonInput.FloatFieldInfinity.ProtobufOutput \
--test Required.Proto3.JsonInput.FloatFieldMaxNegativeValue.ProtobufOutput \
--test Required.Proto3.JsonInput.FloatFieldMaxPositiveValue.ProtobufOutput \
--test Required.Proto3.JsonInput.FloatFieldMinNegativeValue.ProtobufOutput \
--test Required.Proto3.JsonInput.FloatFieldMinPositiveValue.ProtobufOutput \
--test Required.Proto3.JsonInput.FloatFieldNan.ProtobufOutput \
--test Required.Proto3.JsonInput.FloatFieldNegativeInfinity.ProtobufOutput \
--test Required.Proto3.JsonInput.FloatFieldQuotedValue.ProtobufOutput \
--test Required.Proto3.JsonInput.HelloWorld.ProtobufOutput \
--test Required.Proto3.JsonInput.IgnoreUnknownJsonFalse.ProtobufOutput \
--test Required.Proto3.JsonInput.IgnoreUnknownJsonNull.ProtobufOutput \
--test Required.Proto3.JsonInput.IgnoreUnknownJsonNumber.ProtobufOutput \
--test Required.Proto3.JsonInput.IgnoreUnknownJsonObject.ProtobufOutput \
--test Required.Proto3.JsonInput.IgnoreUnknownJsonString.ProtobufOutput \
--test Required.Proto3.JsonInput.IgnoreUnknownJsonTrue.ProtobufOutput \
--test Required.Proto3.JsonInput.Int32FieldExponentialFormat.ProtobufOutput \
--test Required.Proto3.JsonInput.Int32FieldFloatTrailingZero.ProtobufOutput \
--test Required.Proto3.JsonInput.Int32FieldMaxFloatValue.ProtobufOutput \
--test Required.Proto3.JsonInput.Int32FieldMaxValue.ProtobufOutput \
--test Required.Proto3.JsonInput.Int32FieldMinFloatValue.ProtobufOutput \
--test Required.Proto3.JsonInput.Int32FieldMinValue.ProtobufOutput \
--test Required.Proto3.JsonInput.Int32FieldStringValue.ProtobufOutput \
--test Required.Proto3.JsonInput.Int32FieldStringValueEscaped.ProtobufOutput \
--test Required.Proto3.JsonInput.Int32MapEscapedKey.ProtobufOutput \
--test Required.Proto3.JsonInput.Int32MapField.ProtobufOutput \
--test Required.Proto3.JsonInput.Int64FieldMaxValue.ProtobufOutput \
--test Required.Proto3.JsonInput.Int64FieldMaxValueNotQuoted.ProtobufOutput \
--test Required.Proto3.JsonInput.Int64FieldMinValue.ProtobufOutput \
--test Required.Proto3.JsonInput.Int64FieldMinValueNotQuoted.ProtobufOutput \
--test Required.Proto3.JsonInput.Int64MapEscapedKey.ProtobufOutput \
--test Required.Proto3.JsonInput.Int64MapField.ProtobufOutput \
--test Required.Proto3.JsonInput.MessageField.ProtobufOutput \
--test Required.Proto3.JsonInput.MessageMapField.ProtobufOutput \
--test Required.Proto3.JsonInput.MessageRepeatedField.ProtobufOutput \
--test Required.Proto3.JsonInput.OneofFieldNullFirst.ProtobufOutput \
--test Required.Proto3.JsonInput.OneofFieldNullSecond.ProtobufOutput \
--test Required.Proto3.JsonInput.OptionalBoolWrapper.ProtobufOutput \
--test Required.Proto3.JsonInput.OptionalBytesWrapper.ProtobufOutput \
--test Required.Proto3.JsonInput.OptionalDoubleWrapper.ProtobufOutput \
--test Required.Proto3.JsonInput.OptionalFloatWrapper.ProtobufOutput \
--test Required.Proto3.JsonInput.OptionalInt32Wrapper.ProtobufOutput \
--test Required.Proto3.JsonInput.OptionalInt64Wrapper.ProtobufOutput \
--test Required.Proto3.JsonInput.OptionalStringWrapper.ProtobufOutput \
--test Required.Proto3.JsonInput.OptionalUint32Wrapper.ProtobufOutput \
--test Required.Proto3.JsonInput.OptionalUint64Wrapper.ProtobufOutput \
--test Required.Proto3.JsonInput.OptionalWrapperTypesWithNonDefaultValue.ProtobufOutput \
--test Required.Proto3.JsonInput.OriginalProtoFieldName.ProtobufOutput \
--test Required.Proto3.JsonInput.PrimitiveRepeatedField.ProtobufOutput \
--test Required.Proto3.JsonInput.RepeatedBoolWrapper.ProtobufOutput \
--test Required.Proto3.JsonInput.RepeatedBytesWrapper.ProtobufOutput \
--test Required.Proto3.JsonInput.RepeatedDoubleWrapper.ProtobufOutput \
--test Required.Proto3.JsonInput.RepeatedFloatWrapper.ProtobufOutput \
--test Required.Proto3.JsonInput.RepeatedInt32Wrapper.ProtobufOutput \
--test Required.Proto3.JsonInput.RepeatedInt64Wrapper.ProtobufOutput \
--test Required.Proto3.JsonInput.RepeatedListValue.ProtobufOutput \
--test Required.Proto3.JsonInput.RepeatedStringWrapper.ProtobufOutput \
--test Required.Proto3.JsonInput.RepeatedUint32Wrapper.ProtobufOutput \
--test Required.Proto3.JsonInput.RepeatedUint64Wrapper.ProtobufOutput \
--test Required.Proto3.JsonInput.RepeatedValue.ProtobufOutput \
--test Required.Proto3.JsonInput.StringField.ProtobufOutput \
--test Required.Proto3.JsonInput.StringFieldEmbeddedNull.ProtobufOutput \
--test Required.Proto3.JsonInput.StringFieldEscape.ProtobufOutput \
--test Required.Proto3.JsonInput.StringFieldSurrogatePair.ProtobufOutput \
--test Required.Proto3.JsonInput.StringFieldUnicode.ProtobufOutput \
--test Required.Proto3.JsonInput.StringFieldUnicodeEscape.ProtobufOutput \
--test Required.Proto3.JsonInput.StringFieldUnicodeEscapeWithLowercaseHexLetters.ProtobufOutput \
--test Required.Proto3.JsonInput.StringRepeatedField.ProtobufOutput \
--test Required.Proto3.JsonInput.Struct.ProtobufOutput \
--test Required.Proto3.JsonInput.StructWithEmptyListValue.ProtobufOutput \
--test Required.Proto3.JsonInput.TimestampLeap.ProtobufOutput \
--test Required.Proto3.JsonInput.TimestampMaxValue.ProtobufOutput \
--test Required.Proto3.JsonInput.TimestampMinValue.ProtobufOutput \
--test Required.Proto3.JsonInput.TimestampNull.ProtobufOutput \
--test Required.Proto3.JsonInput.TimestampRepeatedValue.ProtobufOutput \
--test Required.Proto3.JsonInput.TimestampWithNegativeOffset.ProtobufOutput \
--test Required.Proto3.JsonInput.TimestampWithPositiveOffset.ProtobufOutput \
--test Required.Proto3.JsonInput.Uint32FieldMaxFloatValue.ProtobufOutput \
--test Required.Proto3.JsonInput.Uint32FieldMaxValue.ProtobufOutput \
--test Required.Proto3.JsonInput.Uint32MapField.ProtobufOutput \
--test Required.Proto3.JsonInput.Uint64FieldMaxValue.ProtobufOutput \
--test Required.Proto3.JsonInput.Uint64FieldMaxValueNotQuoted.ProtobufOutput \
--test Required.Proto3.JsonInput.Uint64MapField.ProtobufOutput \
--test Required.Proto3.JsonInput.ValueAcceptBool.ProtobufOutput \
--test Required.Proto3.JsonInput.ValueAcceptFloat.ProtobufOutput \
--test Required.Proto3.JsonInput.ValueAcceptInteger.ProtobufOutput \
--test Required.Proto3.JsonInput.ValueAcceptList.ProtobufOutput \
--test Required.Proto3.JsonInput.ValueAcceptNull.ProtobufOutput \
--test Required.Proto3.JsonInput.ValueAcceptObject.ProtobufOutput \
--test Required.Proto3.JsonInput.ValueAcceptString.ProtobufOutput \
--test Required.Proto3.JsonInput.WrapperTypesWithNullValue.ProtobufOutput \
--test Required.Proto3.JsonInput.AnyNull.ProtobufOutput \
--test Required.Proto3.JsonInput.AnyWithNoType.ProtobufOutput \
--test Required.Proto3.JsonInput.DoubleFieldQuotedExponentialValue.ProtobufOutput \
--test Required.Proto3.JsonInput.FloatFieldQuotedExponentialValue.ProtobufOutput \
--test Required.Proto3.JsonInput.Int32FieldQuotedExponentialValue.ProtobufOutput \
--test Required.Proto3.JsonInput.Int32FieldStringValueZero.ProtobufOutput \
--test Required.Proto3.JsonInput.TimestampEpochValue.ProtobufOutput \
--test Required.Proto3.JsonInput.TimestampLittleAfterEpochlValue.ProtobufOutput \
--test Required.Proto3.JsonInput.TimestampLittleBeforeEpochValue.ProtobufOutput \
--test Required.Proto3.JsonInput.TimestampNanoAfterEpochlValue.ProtobufOutput \
--test Required.Proto3.JsonInput.TimestampNanoBeforeEpochValue.ProtobufOutput \
--test Required.Proto3.JsonInput.TimestampTenAndHalfSecondsAfterEpochValue.ProtobufOutput \
--test Required.Proto3.JsonInput.TimestampTenAndHalfSecondsBeforeEpochValue.ProtobufOutput \
conformance.sh
